In [14]:
import os
import numpy as np
import pandas as pd
import re
import seaborn as sns
import time

In [3]:
# Import the masses csv

csv_masses = pd.read_csv("C:/Users/nbrittin/Desktop/test/Metallophore_ID/test_masses.csv")

print(csv_masses.shape)
print(csv_masses.head())

(12511, 3)
            Bucket label  MSMS_D937_A_2-E,1_01_20306  \
0  625.30578 Da 120.43 s                      1532.0   
1  278.12929 Da 120.43 s                      4772.0   
2  644.30171 Da 120.43 s                      2360.0   
3  241.17878 Da 120.62 s                     20732.0   
4  150.01609 Da 122.32 s                      1780.0   

   MSMS_D937_R_2-E,2_01_20308  
0                         0.0  
1                         0.0  
2                         0.0  
3                      6504.0  
4                      2064.0  


In [4]:
bucket_labels = csv_masses['Bucket label'].to_list()
print(len(bucket_labels))

masses = []
for i in bucket_labels:
    mass = re.search(r'([0-9]+\.[0-9]+) Da', i).group(1)
    masses.append(float(mass))
print(len(masses))

12511
12511


In [5]:
# Make a subtraction matrix
np.array(masses)
subtraction_matrix = np.absolute(np.subtract.outer(masses, masses))

print(subtraction_matrix)

[[  0.      347.17649  18.99593 ... 259.01429  73.92524 137.9774 ]
 [347.17649   0.      366.17242 ...  88.1622  273.25125 209.19909]
 [ 18.99593 366.17242   0.      ... 278.01022  92.92117 156.97333]
 ...
 [259.01429  88.1622  278.01022 ...   0.      185.08905 121.03689]
 [ 73.92524 273.25125  92.92117 ... 185.08905   0.       64.05216]
 [137.9774  209.19909 156.97333 ... 121.03689  64.05216   0.     ]]


In [6]:
# Convert the matrix to a dataframe
subtraction_matrix_df = pd.DataFrame(subtraction_matrix, columns=masses, index=masses)

In [15]:
# Count all values between 22.98972 and 22.98982
start = time.time()
Na_hit_list = {}
for index, row in subtraction_matrix_df.iterrows():
    for column_name, value in row.items():
        if 21.98190 <= value <= 21.98200:
            row_name = row.name
            key = f"{row_name}_{column_name}"
            Na_hit_list[key] = value
            # Add the value to the dictionary with the row name and column name as the key
            # row_name = row.name
            # column_name = subtraction_matrix_df.columns[i]
            # key = row_name + '_' + column_name
            # value = row[i]
            # Na_hit_list[key] = value
end = time.time()
print("Time taken: " + str(end - start) + " seconds")
print(len(Na_hit_list))
print(Na_hit_list)

Time taken: 37.44426941871643 seconds
198
{'390.13564_412.11761': 21.98196999999999, '424.18536_402.20342': 21.98194000000001, '414.24703_436.22901': 21.98198000000002, '361.22078_383.2027': 21.981920000000002, '867.38378_845.40183': 21.981949999999983, '845.40183_867.38378': 21.981949999999983, '248.10177_226.11981': 21.981959999999987, '586.35252_608.33451': 21.981989999999996, '521.31919_499.33724': 21.98195000000004, '1215.539_1237.52094': 21.981940000000122, '297.68358_319.66557': 21.981989999999996, '584.3486_606.33054': 21.98194000000001, '413.22272_435.20465': 21.981930000000034, '776.37893_754.39702': 21.98190999999997, '480.12003_502.10196': 21.981930000000034, '548.25786_526.27591': 21.981950000000097, '997.48826_975.50629': 21.981969999999933, '1237.52094_1215.539': 21.981940000000122, '606.33054_584.3486': 21.98194000000001, '226.11981_248.10177': 21.981959999999987, '706.34635_684.36442': 21.981930000000034, '500.31872_478.33678': 21.98194000000001, '622.37607_600.39414':

In [26]:
column_names = subtraction_matrix_df.columns.values
row_names = subtraction_matrix_df.index.values

print(column_names[0:10])
print(row_names[0:10])

[625.30578 278.12929 644.30171 241.17878 150.01609 193.07215 174.07933
 206.10314 392.2143  584.31085]
[625.30578 278.12929 644.30171 241.17878 150.01609 193.07215 174.07933
 206.10314 392.2143  584.31085]


In [27]:
data_array = subtraction_matrix
start = time.time()
column_names = subtraction_matrix_df.columns.values
row_names = subtraction_matrix_df.index.values
condition_mask = np.logical_and(data_array >= 21.98190, data_array <= 21.98200)
row_indices, col_indices = np.where(condition_mask)
matching_values_dict = {}
for row_idx, col_idx in zip(row_indices, col_indices):
    key = f"{row_names[row_idx]}_{column_names[col_idx]}"
    matching_values_dict[key] = data_array[row_idx, col_idx]
stop = time.time()
print("Time taken: ", stop - start)
print(len(matching_values_dict))
print(matching_values_dict)


Time taken:  0.931995153427124
198
{'390.13564_412.11761': 21.98196999999999, '424.18536_402.20342': 21.98194000000001, '414.24703_436.22901': 21.98198000000002, '361.22078_383.2027': 21.981920000000002, '867.38378_845.40183': 21.981949999999983, '845.40183_867.38378': 21.981949999999983, '248.10177_226.11981': 21.981959999999987, '586.35252_608.33451': 21.981989999999996, '521.31919_499.33724': 21.98195000000004, '1215.539_1237.52094': 21.981940000000122, '297.68358_319.66557': 21.981989999999996, '584.3486_606.33054': 21.98194000000001, '413.22272_435.20465': 21.981930000000034, '776.37893_754.39702': 21.98190999999997, '480.12003_502.10196': 21.981930000000034, '548.25786_526.27591': 21.981950000000097, '997.48826_975.50629': 21.981969999999933, '1237.52094_1215.539': 21.981940000000122, '606.33054_584.3486': 21.98194000000001, '226.11981_248.10177': 21.981959999999987, '706.34635_684.36442': 21.981930000000034, '500.31872_478.33678': 21.98194000000001, '622.37607_600.39414': 21.981

In [29]:
column_names = subtraction_matrix_df.columns.values
row_names = subtraction_matrix_df.index.values
start = time.time()
iron_condition_mask = np.logical_and(data_array >= 54.9265, data_array <= 54.9276)
row_indices, col_indices = np.where(iron_condition_mask)
iron_hits = {}
for row_idx, col_idx in zip(row_indices, col_indices):
    key = f"{row_names[row_idx]}_{column_names[col_idx]}"
    iron_hits[key] = data_array[row_idx, col_idx]
end = time.time()
print(f"Time elapsed: {end - start} seconds")
print(f"Number of hits: {len(iron_hits)}")
print(iron_hits)

Time elapsed: 0.9332315921783447 seconds
Number of hits: 424
{'381.18916_326.26239': 54.92677000000003, '682.32069_627.39398': 54.92670999999996, '321.2046_376.13124': 54.92663999999996, '221.16381_276.09079': 54.926980000000015, '263.04665_208.1196': 54.92705000000001, '402.13609_347.20888': 54.92721, '979.4339_924.50692': 54.92697999999996, '329.23149_384.15805': 54.926559999999995, '558.33686_613.26399': 54.927130000000034, '767.35852_712.43096': 54.92755999999997, '387.18322_332.25613': 54.92709000000002, '558.18527_503.25775': 54.92751999999996, '752.30917_697.38232': 54.926849999999945, '1100.54258_1155.46908': 54.92650000000003, '611.2174_556.29027': 54.927130000000034, '561.28258_616.20976': 54.92717999999991, '367.21541_312.28848': 54.92693000000003, '1030.55728_975.63063': 54.926649999999995, '398.19862_343.27168': 54.92694, '398.19862_343.27149': 54.927130000000034, '727.38568_672.45824': 54.92743999999993, '329.23105_384.15805': 54.92700000000002, '706.28302_651.35583': 54.